apache/skywalking-eyes

- .golangci.yml
- .licenserc.yaml
- license-eye/commands/header/check.go
- license-eye/commands/header/fix.go
- license-eye/internal/logger/log.go
- license-eye/pkg/header/check.go
- license-eye/pkg/header/check_test.go
- license-eye/pkg/header/config.go
- license-eye/pkg/header/fix.go
- license-eye/pkg/license/norm.go
- license-eye/pkg/license/norm_test.go
- license-eye/pkg/result.go
With the normalizations, it's rare that `pattern` needs to be configured, this minimize the configurations and ease the usage
> Refactor the normalizers to increase accuracy and minimize the use of pattern

- README.md
- quality-eye/README.md
This patch creates a sub-directory to host the new E2E framework codes, @fgksgf @Humbertzhang , let's host the codes here instead of in the CLI repo, they are independent after all.
@wu-sheng this also demonstrates how we organize different tools in this repo, we may have "release-eye" (checking gpg / sha512, etc.) in the future that stands alongside "license-eye", "quality-eye", etc.. Hope the structures make sense to you
> Shape the quality-eye sub-directory for NGE2E

- go.sum
- pkg/deps/golang.go
- pkg/deps/resolve.go
- pkg/deps/result.go
- pkg/license/identifier.go
This PR adds a pattern to identify dual-license and skip resolving built-in package's licenses
> Identify some of dual licenses and skip built-in packages' licenses

- README.md
Fix the inaccurate description of README.md, the `Compile from Source` in README.md is incorrect, and there is no license-eye directory in the skywalking-eyes directory.
> Fix the inaccurate description of README.md.

- .golangci.yml
- pkg/review/header.go
Discovered in https://github.com/apache/skywalking/pull/6467/checks?check_run_id=1994138869 (though there is naming issue in that PR)
> defect: avoid crash when no comment style is found

- pkg/config/config.go
- pkg/header/check.go
Reading an file named `""` will raise the `IsNotExist` error, so the conditional statement is unnecessary in `pkg/config/config.go`
The result should match whether the pattern is `.` or `./`.
Small improvement.
> Fix minor error

- assets/languages.yaml
The `.ts` (TypeScript) CommentStyle is already defined in Line 5819 of this file and should be `SlashAsterisk`.
> Fix typescript file license header fix to use SlashAsterisk instead of AngleBrackets

- assets/assets.go
The embeded file system `embed.FS` only takes the forward slash (`/`) as the path separator. However, the operating system path separator in Windows is the backward slash (`\`). We need to normalize the file path separator each time we use `embed.FS`.
>  fix some program compatibility issues in Windows

- pkg/deps/npm.go
- pkg/deps/resolve.go
1. Parse the project package.json file to gather the required packages
2. Run command 'npm install' to install or update the required node packages (can skip)
3. Walk through each package's root directory to resolve licenses
- STEP 1: Try to find and parse the package.json file to capture the license field
- STEP 2: Try to find the license file to identify the license
> Add support for resolving npm dependencies' licenses

- pkg/deps/npm.go
This patch enhances the NPM dependency resolver to resolve all the dependent packages.
First, it runs the npm command `npm ls --all --parseable` to list all the packages' absolute paths.
Then, each package's name is inferred from its relative path from the node_modules dir.
Finally, walk through each package's root path to resolve licenses from the package.json file or the license file.
> Enhance NPM dependency resolver to resolve all the dependent packages

- pkg/deps/npm.go
- pkg/deps/npm_test.go
This patch enhances the NPM dependency resolver to resolve deprecated license styles, which are like
```
{
"license" : {
"type" : "ISC",
"url" : "https://opensource.org/licenses/ISC"
}
}
{
"licenses" : [
{
"type": "MIT",
"url": "https://www.opensource.org/licenses/mit-license.php"
},
{
"type": "Apache-2.0",
"url": "https://opensource.org/licenses/apache2.0.php"
}
]
}
```
> Enhance NPM dependency resolver to resolve deprecated license styles

- README.md
- assets/compatibility/Apache-2.0.yaml
- commands/deps_check.go
- commands/deps_resolve.go
- pkg/deps/check.go
- pkg/license/identifier_test.go
- pkg/license/norm.go
The compatible matrix needs further polishes, but his sets up the mechanism.
> Set up mechanism to check dependencies' license compatibilities

- Dockerfile
we don't need the entire golang development environment, instead, we only need the golang CLI tool to help us resolve packages.
> Reduce Docker image size and add npm env to resolve npm projects' dependencies

- README.md
- assets/languages.yaml
- test/testdata/include_test/with_license/testcase.pyx
- test/testdata/include_test/without_license/testcase.pyx
Relates to #7552
Modified:
* `assets/languages.yaml`
* Added `comment_style_id` to cython section
* `README.md`
* Corrected link/description indicating `languages.yaml` instead of `styles.yaml`
* Some whitespace trimming occurred (sorry)
Added test files for `*/pyx`:
```
test/testdata/include_test/with_license/testcase.pyx
test/testdata/include_test/without_license/testcase.pyx
```
Confirmed working via local docker build and testing against file indicated in https://github.com/apache/skywalking/issues/7552
> add comment type to cython declaration

- assets/languages.yaml
`comment_style_id` for Rust was added in #29, but currently, running `header fix` for Rust files does not work and displays `unsupported files: ...`.
The language configuration file contains two entries for the `.rs` file extension: RenderScript and Rust. `.rs` files end up matching RenderScript, which does not have a comment style. Locally, I fixed this for Rust by removing RenderScript from the language configuration file.
However, in this PR, I choose to set the command style for RenderScript to double slash, which is supported by both languages (and actually the [preferred](https://github.com/rust-lang/book/issues/693#issuecomment-301200629) style for Rust).
> Fix file extension conflict between RenderScript and Rust

- assets/languages.yaml
- assets/styles.yaml
- pkg/comments/config_test.go
- pkg/header/fix_test.go
Closes https://github.com/apache/skywalking/issues/7569
FYI @mikhail-dr
> Honor Python's coding directive

- README.md
- commands/deps_resolve.go
This is a missing but important feature that helps to organize the distribution package especially in ASF projects, it resolves and saves all LICENSE files of the dependencies.
> feature: support saving dependencies' licenses

- commands/deps_resolve.go
During resolving licenses, the working directory of the process would change. In this situation, if the `output` location a user inputed is a relative path, then the saving location would be different from what it was defined at first.
> fix the save location problem

- pkg/deps/npm.go
- pkg/deps/npm_test.go
- pkg/deps/result.go
This patch eanhances Npm resolver to record each pkg's license contents. In previous versions, Npm resolver will not record the license content when it identifies a pkg's license through the package.json file. Now, it will still resolve a pkg's license info through its package.json file first. Also, whether or not the previous step succeeded, it will try to locate a pkg's LICENSE file and record its content.
> Enhance Npm Resolver: support recording license contents

- assets/languages.yaml
This is currently breaking my TypeScript codebase. I'm going to upstream this for y'all to land.
> Remove .tsx from XML language extensions

- assets/languages.yaml
I realized this was missing from my other PR. This is necessary to have the tool automatically add the License comment to the top of the file.
> Add Comment Style for TypeScript language support

- pkg/license/identifier.go
We have many license template files to load at initialization phase, this speeds up the initialization phase from 8s to 2s
```
pwd                                                        
/Users/kezhenxu94/workspace/skywalking-infra-e2e
```
```
time ~/workspace/skywalking-eyes/bin/darwin/license-eye h c
INFO GITHUB_TOKEN is not set, license-eye won't comment on the pull request 
INFO Loading configuration from file: .licenserc.yaml 
INFO Totally checked 2336 files, valid: 59, invalid: 0, ignored: 2277, fixed: 0 
================
CPU	108%
user	8.451
system	0.351
total	8.146
time ~/workspace/skywalking-eyes/bin/darwin/license-eye h c
INFO GITHUB_TOKEN is not set, license-eye won't comment on the pull request 
INFO Loading configuration from file: .licenserc.yaml 
INFO Totally checked 2336 …
```
> Speed up the initialization phase

- README.md
- action.yml
This PR is a small change which adds an additional, optional, input to the action called `mode`. My goal with this change is to make it so CI pipelines can automatically apply the licenses to PRs which lack them (applying the changes would be handled by a different action like [this one](https://github.com/EndBug/add-and-commit)). I looked around and did not see any mention of such functionality; apologies if I missed it.
Some additional notes:
- `mode` can take one of two values: `check` or `fix`. I set the default to `check` to preserve existing behavior.
- I have also updated the README with the new input description. 
- I see from the diff that my IDE removed some trailing spaces; if you really want those back I can redo the changes with vim or something
- I have tested that this …
> Adds an option to the action to run in "fix" mode

- Makefile
- commands/deps_resolve.go
- pkg/deps/golang.go
- pkg/deps/npm.go
- pkg/header/check.go
- pkg/header/fix.go
- pkg/review/header.go
Noticed the lint error on https://github.com/apache/skywalking-eyes/pull/87, it is caused by we were using the latest lint, but the rules change from time to time.
Lock it to v1.43.0 this time, and fix the gap between the last build and v1.43.0
> Lock version of golangci-lint to 1.43.0. And fix lint issue.

- assets/header-templates/MPL-2.0.txt
Hi there, thanks for this great project! I am using the MPL in some places, and so would love built-in support for it. It's really nice that it was so easy to use a `content` block to get started, but I figured upstreaming this would be nice :) 
I am not sure if I should be adding a test or anything, happy to make any modifications you'd like. I did verify that this works by running my branch against a sample codebase, you can see that result here: https://github.com/steveklabnik/ci-license-test/pull/4
> Add MPL-2.0 header template

- assets/languages.yaml
Add comment style for HCL (Terraform) to enable `header fix` support
https://www.terraform.io/language/syntax/configuration#comments
> Add comment style for HCL (Terraform)

- test/content_test.go
- test/testdata/spdx_content_test/testcase.go
- test/testdata/spdx_content_test/testcase.graphql
- test/testdata/spdx_content_test/testcase.ini
- test/testdata/spdx_content_test/testcase.java
- test/testdata/spdx_content_test/testcase.ml
- test/testdata/spdx_content_test/testcase.php
- test/testdata/spdx_content_test/testcase.pl
- test/testdata/spdx_content_test/testcase.py
- test/testdata/spdx_content_test/testcase.pyx
- test/testdata/spdx_content_test/testcase.sh
- test/testdata/spdx_content_test/testcase.yaml
- test/testdata/spdx_content_test/testcase.yml
- test/testdata/test-spdx-content.yaml
Signed-off-by: tison <wander4096@gmail.com>
This closes https://github.com/apache/skywalking/issues/7757.
> test: add tests for bare spdx license header content

- pkg/deps/jar_test.go
- pkg/deps/maven_test.go
- pkg/deps/npm_test.go
A small testing enhancement.
We can use the `T.TempDir` function from the `testing` package to create temporary directory. The directory created by `T.TempDir` is automatically removed when the test and all its subtests complete. 
Reference: https://pkg.go.dev/testing#T.TempDir
> test: use `T.TempDir` to create temporary test directory

- README.md
- commands/deps_resolve.go
- pkg/deps/config.go
- pkg/deps/golang.go
- pkg/deps/jar.go
- pkg/deps/jar_test.go
- pkg/deps/maven.go
- pkg/deps/maven_test.go
- pkg/deps/npm.go
- pkg/deps/npm_test.go
- pkg/deps/resolve.go
- pkg/deps/summary.go
- pkg/license/identifier.go
Follow https://github.com/apache/skywalking/discussions/8992, I have done two things:
1. Add a new flag `--summary` to help users generate the license summary file by template file. 
2. Add `licenses` config under the `dependency` to declare which license is could not be recognized.
> Provide `--summary` flag to generate the license summary file

- .licenserc.yaml
- README.md
- pkg/deps/golang.go
- pkg/deps/jar.go
- pkg/deps/jar_test.go
- pkg/deps/maven.go
This is also a bug that when there is no LICENSE file in dependency folder, the `licenses` doesn't work.
> dep: short circuit if user declare dep license

- README.md
If users use this demo as a copy, the indents issue in the action demo will lead to the failure of action.
According to the [docs](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-7), the `with` has the same indents with `uses`, so just remove the extra indents in the demo.
> [docs] Fix the indents issue in the action demo

- pkg/review/header.go
So the logs can respect the `--verbosity` config.
Closes https://github.com/apache/skywalking/issues/9172
> Lazy initialize GitHub client for comment

- README.md
- pkg/deps/config.go
- pkg/deps/golang.go
- pkg/deps/maven.go
- pkg/deps/npm.go
- pkg/deps/result.go
This can be helpful when users want to exclude some dependencies that they don't care (for example, self modules in maven project, some dependencies that they don't re-distribute).
Also some minor refactoring
> Add `excludes` to `license resolve` config

- README.md
- commands/deps_check.go
- commands/deps_resolve.go
- commands/header_check.go
- commands/header_fix.go
- commands/root.go
- pkg/config/config.go
- pkg/review/header.go
- test/config_test.go
- test/testdata/multiple_license_test/pkg/a/main.go
- test/testdata/multiple_license_test/pkg/b/main.go
- test/testdata/test-multiple.yaml
This allows for multiple `license` configurations to be contained
within the same .licenserc.yaml file. The intended use is for a project
that has multiple packages or modules with differing licenses.
To do this we introduce a ConfigV2 config format since it is not valid
YAML for a key to be either a dictionary or a sequence.
We try to parse as V2 first, and fall back to V1.
> Add support for multiple licenses in the header config section

- pkg/deps/npm.go
This will prune extraneous dependencies as stated in https://docs.npmjs.com/cli/v7/commands/npm-prune
> Prune packages before listing all dependencies

- assets/header-templates/GPL-3.0-or-later.txt
- pkg/header/config.go
Created new header template for SPDX identifier `GPL-3.0-or-later`
> New Header Template: GPL-3.0-or-later

- .github/workflows/publish-docker.yaml
- Makefile
resolves apache/skywalking#9089
- Added feature to create docker multiple architectures images (linux/amd64 and linux/arm64)
> Docker Multiple Architecture Support :fixes#9089

- LICENSE
- pkg/deps/jar_test.go
- pkg/deps/maven_test.go
- pkg/deps/testdata/maven/.mvn/wrapper/maven-wrapper.properties
- pkg/deps/testdata/maven/mvnw
Now we can debug the identification in the test, which makes it simple to debug why we failed to identify the license of a dependency
> Polish maven test for convenient debug

- pkg/deps/npm.go
According to https://blog.npmjs.org/post/171556855892/introducing-npm-ci-for-faster-more-reliable, one should prefer `npm ci` over `npm install` for more reliable builds, so all the versions can be locked exactly unless we explicitly upgrade them.
> Switch to npm ci for reliable builds

- pkg/deps/maven.go
- pkg/deps/maven_test.go
Optional dependencies should be excluded but they are not because of regexp missing the optional part
```
[INFO] +- org.mariadb.jdbc:mariadb-java-client:jar:2.7.2:provided (optional) 
```
> Fix optional dependencies are not excluded

- README.md
- pkg/deps/cargo.go
- pkg/deps/config.go
- pkg/deps/golang.go
- pkg/deps/maven.go
`dependency.excludes` doesn't work for transitive dependencies so this might bring some dependencies that users want to exclude.
This patch also adds a `recursive` config so users can decide whether to only exclude one dependency or also exclude all dependencies brought by this dependency.
/cc @jmjoy currently it seems Rust (cargo.go) only resolve direct dependencies, not including transitive dependencies, so we might miss some transitive dependencies in the license report.
/cc and thanks to @slievrly for reporting this bug
> Fix exclude not work for transitive dependencies and add recursive config

- commands/deps_resolve.go
Some dependencies can be identified and they are manually specified by `dependency.licenses`, in this case, the license file cannot be copied correctly, we have to again manually copy these license files but we don't want the license eye command to override these files.
> dep: do not write license files if they already exist

- pkg/license/norm.go
As we are using `license-eyes` to check license header in our open-sourced projects, we notice that it can help detect 
unexpected changes in the license header, *except the copyright line*. In my opinion, it's also necessary to protect the copyright line from unintentional changes.
https://github.com/apache/skywalking-eyes/pull/46 introduced this line processor to ignore copyright line, mostly for the purpose of dependency resolution. However, in https://github.com/apache/skywalking-eyes/pull/107 starts using Google's license check for this purpose, and this line processor only works to ignore copyright line when checking / fixing license header.
@kezhenxu94
> fix license header normalizer

- pkg/deps/golang.go
- pkg/deps/maven.go
When using output file to store the dependency tree, `dependency:tree` emits a cleaner tree with effective pom file, this reduces unused dependencies in result
> dep/maven: use output file to store the dep tree for cleaner result

- Makefile
- action.yml
This greatly shorten the waiting time;
- first run (~24s)
- non first run (~4s)
Compared to previous Docker running mode
> gha: switch to composite running mode and set up cache

- pkg/deps/cargo.go
- pkg/deps/cargo_test.go
Sometimes the dependent license is not standardized in cargo (not follow [SPDX](https://spdx.dev/)), such as `MIT/Apache-2.0`, or not sorted, like `MIT OR Apache-2.0`. 
It is impossible to combine the dependencies of the same license at the time of summary.
This PR is to normalize the license and normalize `MIT/Apache-2.0` and `MIT OR Apache-2.0` into `Apache-2.0 OR MIT`.
> Normalize license for cargo.

- assets/compatibility/Apache-2.0.yaml
- pkg/deps/check.go
- pkg/deps/check_test.go
Also polish the summary of `dep check` command, add MIT to Apache 2.0 compatibility matrix.
> Dependencies check should report unknown licneses

- README.md
Closes https://github.com/apache/skywalking/issues/10748
> Fix wrong indentation in doc about multi license config

- pkg/license/norm.go
Following up on the changes performed at https://github.com/apache/skywalking-eyes/pull/142, this PR is removing another regex that is causing the whole copyright line to be removed by the normalizer (due to the `.+$` match) if the line contains `Portions Copyright`.
closes https://github.com/apache/skywalking/issues/11218
cc @kezhenxu94
> Remove "portions copyright" header normalizer

- assets/compatibility/Apache-2.0.yaml
- commands/deps_check.go
- pkg/deps/check.go
- pkg/deps/check_test.go
This PR is based on this discussion: https://github.com/apache/skywalking/discussions/11391.
A new list called `weak-compatible` is added to the [skywalking-eyes compatibility list](https://github.com/apache/skywalking-eyes/blob/main/assets/compatibility/Apache-2.0.yaml). 
A new flag called `weak-compatible` is added to the `dependency check` command.
> update: add weak-compatible to dependency check

- assets/header-templates/Apache-2.0-EF.txt
As per the [Eclipse Project Handbook](https://www.eclipse.org/projects/handbook/#ip-copyright-headers)
> add Eclipse Foundation specific Apache 2.0 license header

- .github/workflows/license-eye-check.yaml
- action.yml
- dependency/action.yml
- header/action.yml
fixes the following warning:
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/setup-go@v4. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
> bump action/setup-go to v5

- README.md
Add instructions for installing license-eye using Homebrew on macOS
> Add instructions for installing license-eye using Homebrew on macOS

- .github/workflows/license-eye-check.yaml
- .golangci.yml
- Makefile
- README.md
- action.yml
- commands/deps_check.go
- commands/deps_resolve.go
- commands/header_check.go
- commands/header_fix.go
- commands/root.go
- dependency/action.yml
- examples/golang/Dockerfile
- examples/java/Dockerfile
- examples/nodejs/Dockerfile
- go.mod
- header/action.yml
- pkg/deps/jar.go
- pkg/deps/maven.go
- pkg/header/check.go
Dependencies license check depends on different programming language env and version, it’s unreasonable to include the env in the Docker image by default, this PR cleans the programming language tools from the Docker images to reduce the size from 350+M to ~36M
> Bump up to go 1.23 and clean up Docker images

- README.md
- Record the use of SkyWalking Eyes Docker Image under PowerShell 7.
- This is a discovery from https://github.com/linghengqian/hive-server2-jdbc-driver/pull/28 . `$(pwd)` is not available under PowerShell 7, and I think proper documentation will help Windows 11 users.
> Record the use of SkyWalking Eyes Docker Image under PowerShell 7

- assets/compatibility/Apache-2.0.yaml
I found that EPL-1.0 appears in both the "compatible" and "weak-compatible" lists. Perhaps what we intended to write in the "compatible" list was EDL-1.0 (Eclipse Distribution License 1.0)? 
Also, add MIT-0 (MIT No Attribution) and 0BSD (Zero-Clause BSD) to the "compatible" list.
> Add few missing compatible licenses for dependency check

- pkg/deps/ruby.go
- pkg/deps/ruby_test.go
- regression test: Ruby library projects with no runtime dependencies do not include development dependencies
> GemfileLockResolver adjusted to exclude all specs when runtime dependencies are empty

- assets/compatibility/Apache-2.0.yaml
- assets/compatibility/MIT.yaml
- assets/compatibility/Ruby.yaml
- pkg/deps/category_matrix_test.go
Category A license: MIT
- SPDX: https://spdx.org/licenses/MIT.html
Category B license: Ruby
- SPDX: https://spdx.org/licenses/Ruby.html
(Update) Category A license: Apache-2.0
- SPDX: https://spdx.org/licenses/Apache-2.0.html
(test) MIT (Cat A) and Ruby (Cat B) license compatibility matrix
> feat: Compatibility matrix: MIT & Ruby

- README.md
Allow weak-compatible for Ruby
- Ruby packages declared as dependencies in gemspecs or Gemfiles are typically consumed as binaries; 
- enable weak-compatibility so permissive and weak-copyleft combinations are treated as compatible
NOTE: I've blogged about how to set up a Ruby project specifically, but it is broadly applicable:
https://dev.to/galtzo/how-to-check-license-compatibility-41h0
> Update example workflow in the README for the Ruby scenario
