apache/skywalking-eyes

- .github/workflows/license-eye-check.yaml
- .licenserc.yaml
- license-eye/commands/header/check.go
- license-eye/go.mod
- license-eye/go.sum
- license-eye/pkg/header/config.go
- license-eye/pkg/header/fix.go
- license-eye/pkg/header/fix_test.go
- license-eye/pkg/review/header.go
Example https://github.com/kezhenxu94/skywalking-cli/pull/4
> Add new feature to review the pull request and suggest adding license headers

- Dockerfile
- README.md
The docker image is really large, still pushing....
> Add documentation about how to use via docker image

- pkg/license/norm.go
> enhance: tolerate leading whitespaces in license header

- assets/languages.yaml
- assets/styles.yaml
- pkg/license/norm.go
As discussed in #41 and should/must be merged before it.
> Add support of apostrophe style comments for PlantUML

- .golangci.yml
- commands/root.go
- pkg/config/config.go
- pkg/deps/golang.go
- pkg/deps/maven.go
- pkg/deps/maven_test.go
- pkg/header/check.go
- pkg/header/config.go
- pkg/header/fix.go
- pkg/header/fix_test.go
- pkg/review/header.go
Also replace deprecated linter with recommended and fix issues found by new linter.
Closes https://github.com/apache/skywalking/issues/7556
> header fix: respect user configured license content

- .gitignore
- pkg/header/config.go
Closes https://github.com/apache/skywalking/issues/7543
> Resolve absolute path in `.gitignore` to relative path

- assets/languages.yaml
This PR adds the comment style for CMake so that fix can fix it.
> Add Comment Style for CMake Language

- README.md
[Docs]Correct spelling mistakes.
> [Docs]Correct spelling mistakes.

- assets/styles.yaml
Closes https://github.com/apache/skywalking/issues/7547
> Add Python DocString comment style

- .gitignore
- Makefile
Closes https://github.com/apache/skywalking/issues/7845
> Add .exe suffix to windows binary

- assets/languages.yaml
Signed-off-by: tison <wander4096@gmail.com>
> Support fix license header for tcl files

- commands/header_check.go
Now we have a summary just in the summary page, no need to click into the logs and check the logs
> Add GitHub Action step summary for better experience

- pkg/deps/check.go
- pkg/deps/check_test.go
Fix https://github.com/apache/skywalking/issues/9319.
> Support license expression in dep check.

- assets/header-templates/Apache-2.0.txt
- pkg/header/config_test.go
- test/config_test.go
see https://www.apache.org/licenses/LICENSE-2.0
> Correct indent in Apache-2.0 template

- action.yml
- dependency/action.yml
- header/action.yml
Same as the one in infra-e2e repo
> Leverage the built-in cache in setup-go@v4

- README.md
closes https://github.com/apache/skywalking/issues/10746
> Fix wrong indentation in doc

- assets/header-templates/EPL-2.0.txt
Closes https://github.com/apache/skywalking/issues/10764#event-9176828546
FYI @heliocastro
> Add EPL-2.0 header template

- pkg/license/norm.go
closes https://github.com/apache/skywalking/issues/11302
> Add `|` as comment indicator

- pkg/review/header.go
This makes it easier for users to quickly fix up issues
> add instructions to fix header issues in markdown comment

- assets/compatibility/Apache-2.0.yaml
According to the https://spdx.org/licenses/BSD-2-Clause-Views.html, the license is 'identical to BSD-2-Clause with the addition of the "views and conclusions" sentence at the end'
> Update Apache-2.0.yaml to add BSD-2-Clause-Views

- pkg/deps/ruby.go
- pkg/deps/ruby_test.go
- now treats missing specs as unresolved licenses
- adds them to the invalid list
- License fetch logic handles empty gem versions gracefully
- tests updated
- handle missing specs gracefully with mocked HTTP responses
- imports and packages were refactored to enable mocking and improve test structure
> Fixed nil dependency panic in Ruby Gemfile.lock resolver
